[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 8501

[theme]
base = "light"
primaryColor = "#1f77b4"

[client]
showErrorDetails = true
toolbarMode = "minimal"
